inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: "2.4"
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Gemfile'
    - 'typesense.gemspec'

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
